# Generated by Django 5.0.4 on 2024-04-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='floor',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
